//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware_Store_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Closing_application
    {
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public int IdMakinganapplication { get; set; }
        public int IdStaffofemployees { get; set; }
    
        public virtual Making_an_application Making_an_application { get; set; }
        public virtual Staff_of_employees Staff_of_employees { get; set; }
    }
}
