//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware_Store_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WTFTutorial2Entities6 : DbContext
    {
        public WTFTutorial2Entities6()
            : base("name=WTFTutorial2Entities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Closing_application> Closing_application { get; set; }
        public virtual DbSet<Making_an_application> Making_an_application { get; set; }
        public virtual DbSet<Staff_of_employees> Staff_of_employees { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
